### ISSUE TITLE
Upload to personal ftp server

### ISSUE THREAD

**Issue by deedeeharris** [bluegreen-labs/phenocam_installation_tool#22]
Hello. I used the PIT tool to configure my phenocam. I was wondering how can I upload the images to my personal ftp server? Where do I configure the server, port, username, and password? In the settings camera's available in the browser? Or I have to edit some config file manually? 

Thanks.

**Comment by patricktokeeffe** [comment]
An easier method would be edit the configuration file `server.txt` after running the installation script. You can do this with the web interface (advanced > manual config > edit server.txt) or using Telnet & a text editor. Just be sure to `save` the configuration changes when finished.

````diff
-phenocam.nau.edu
+your.server.address.xzy
````

**Comment by deedeeharris** [comment]
> An easier method would be edit the configuration file `server.txt` after running the installation script. You can do this with the web interface (advanced > manual config > edit server.txt) or using Telnet & a text editor. Just be sure to `save` the configuration changes when finished.
> 
> ```diff
> -phenocam.nau.edu
> +your.server.address.xzy
> ```

Thanks! And where do enter the username and password?

**Comment by patricktokeeffe** [comment]
User and password are defined in several other files {`ftp.scr`, `IR_ftp.scr`, `IP_ftp.scr`}. 

If you follow the 3rd party network directions, then you only need to edit one file (the install script) plus the camera configurations get backed up on the FTP server too. The trick is hosting the installer `.tar.gz` package at the right location: it requires an http:// server and the file path must be `<HOST>/data/configs/phenocam_default_install.tar.gz`

**Comment by deedeeharris** [comment]
Thanks!

In which file on the phenocam, can I edit how often the camera takes an
image manually?

Thanks,
Yedidya

**Comment by khufkens** [comment]
Sorry, didn't check this repo for a while. This is in the crontab file.
